# Generated by Django 4.0.4 on 2022-06-18 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tinymodel',
            name='alias',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
