# Generated by Django 4.0.4 on 2022-06-18 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_tinymodel_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tinymodel',
            name='alias',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
